version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: paycraft-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: paycraft_db
      MYSQL_USER: paycraft_user
      MYSQL_PASSWORD: paycraft_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema:/docker-entrypoint-initdb.d
    networks:
      - paycraft-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PayCraft Backend Application
  paycraft-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paycraft-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Database Configuration
      DATABASE_NAME: paycraft_db
      DATABASE_USERNAME: paycraft_user
      DATABASE_DEV_PASSWORD: paycraft_password
      
      # Security
      SECRET_STRING: PAYHFUKNSF09839FELIKS9348J39GHIUEWFJR9EF089WUJ4FNR9HG738UJW4WOLLSTONECRAFT
      ENCRYPTION_KEY: qdwgtxpX5kRyNzua8eV2WwQrvTu3bP9F
      
      # KoraPay Configuration (Use test keys)
      KORA_SECRET_KEY: sk_test_cNNwP1m6g3iDBFDjVDFL7xLFTsgL3WZ2HCsn3diK
      KORA_PUBLIC_KEY: pk_test_i9LYCDrBR3dfe6AfZhjsSLn7XFxWYR8bUy5yPBPQ
      
      # Email Configuration
      EMAIL_SENDER: noreply@paycraft.com
      EMAIL_PASSWORD: your_app_password_here
      
      # Frontend URL
      FRONTEND_URL: http://localhost:3000
      
      # Webhook URLs
      WEBHOOK_URL: http://localhost:6020
      WEBHOOK_DEV_URL: http://localhost:6020/webhook/
      
      # Spring Profile
      SPRING_PROFILES_ACTIVE: dev
      
      # Database URL for Docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paycraft_db
      SPRING_DATASOURCE_USERNAME: paycraft_user
      SPRING_DATASOURCE_PASSWORD: paycraft_password
      
    ports:
      - "6020:6020"
    networks:
      - paycraft-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6020/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis (for caching - optional enhancement)
  redis:
    image: redis:7-alpine
    container_name: paycraft-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paycraft-network
    command: redis-server --requirepass paycraft_redis_password

  # Nginx Reverse Proxy (for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: paycraft-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - paycraft-backend
    networks:
      - paycraft-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  paycraft-network:
    driver: bridge