spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql-1efceed6-bakaredavid007-2598.d.aivencloud.com:11165/${DATABASE_NAME:defaultdb}
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
logging:
  file:
    name: log/paycraft-service-dev.log
  level:
    org:
      springframework:
        security: DEBUG

secret-string: ${SECRET_STRING:PAYHFUKNSF09839FELIKS9348J39GHIUEWFJR9EF089WUJ4FNR9HG738UJW4WOLLSTONECRAFT}
kora-secret: ${KORA_SECRET_KEY}
webhook-dev-url: ${WEBHOOK_URL}
encryption-key: ${ENCRYPTION_KEY}
kora-public: ${KORA_PUBLIC_KEY}
frontend:
  url: ${FRONTEND_URL:https://paycraft-dev.netlify.app/}

server:
  port: 6020
  error:
    include-message: always