spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost/${DATABASE_NAME:paycraft}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
logging:
  file:
    name: log/paycraft-service-dev.log
  level:
    org:
      springframework:
        security: DEBUG

secret-string: ${SECRET_STRING:}
kora-secret: ${KORA_SECRET_KEY:sk_test_cNNwP1m6g3iDBFDjVDFL7xLFTsgL3WZ2HCsn3diK}
webhook-url: ${WEBHOOK_URL:"https://paycraft-development-backend-v1.onrender.com"}
encryption-key: ${ENCRYPTION_KEY:qdwgtxpX5kRyNzua8eV2WwQrvTu3bP9F}
kora-public: ${KORA_PUBLIC_KEY:pk_test_i9LYCDrBR3dfe6AfZhjsSLn7XFxWYR8bUy5yPBPQ}
webhook-dev-url: ${WEBHOOK_DEV_URL:https://paycraft-development-backend-v1.onrender.com/webhook/}

frontend:
  url: ${FRONTEND_URL:https://paycraft-dev.netlify.app/}

# Disable mail health check for local development
management:
  health:
    mail:
      enabled: false

server:
  port: 6020
  error:
    include-message: always
