spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://paycraft-dev-aalto.h.aivencloud.com:14641/${DATABASE_NAME:defaultdb}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
logging:
  file:
    name: log/paycraft-service-dev.log
  level:
    org:
      springframework:
        security: DEBUG

secret-string: ${SECRET_STRING:PAYHFUKNSF09839FELIKS9348J39GHIUEWFJR9EF089WUJ4FNR9HG738UJW4WOLLSTONECRAFT}

server:
  port: 6020
  error:
    include-message: always