spring:
  mail:
    host: smtp.gmail.com 
    port: 465
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    enable: true
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  application:
    name: PayCraft
  profiles:
    active: dev

payroll:
  job:
    fixedRate: 300000

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}